### ISSUE TITLE
Checklist to v3.0.0

### ISSUE THREAD

**Issue by pkkid** [pkkid/python-plexapi#124]
Lets use this as a checklist of things we want before releasing v3.0.0.

- [ ] Close Bug #109 - New Automated Tests.
- [x] Close Bug #62 - Displaying Photos in Nested Photoalbums.
- [ ] Close Bug #32 - Add ability to add/remove items from Collections.
- [x] Close Bug #125 - Support Plex Server Settings.
- [x] Parse Examples Into py.test and Docs.

**Comment by pkkid** [comment]
Closing this one, we can use tags to track.
